<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Choose Your Style | Creatique</title>
<style>
:root{--bg:#090811;--panel:#151121;--line:#302443;--text:#f7f2ff;--muted:#b9aecb;--purple:#8b5cf6}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(ellipse at 10% 0%,#281542 0,transparent 35%),var(--bg);color:var(--text);font:15px/1.5 Inter,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}
.navbar{height:72px;padding:0 max(22px,calc((100% - 1160px)/2));display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #302443;background:#0c0914;position:sticky;top:0;z-index:2}.brand{font-size:1.4rem;font-weight:850;letter-spacing:-.6px}.brand span{color:#b794ff}.nav-link{padding:10px 14px;border-radius:10px;color:#d3c7e8;font-weight:750}.nav-link:hover{background:#211735}
.wrap{width:min(1120px,calc(100% - 36px));margin:auto;padding:55px 0 65px}.hero{text-align:center;max-width:720px;margin:0 auto 34px}.eyebrow{display:inline-block;padding:7px 12px;border:1px solid #503675;border-radius:99px;background:#1b122a;color:#d8b4fe;font-size:.74rem;font-weight:850;letter-spacing:1.3px}.hero h1{font-size:clamp(2.1rem,5vw,3.5rem);line-height:1.08;letter-spacing:-1.8px;margin:18px 0 12px}.hero h1 span{color:#b794ff}.hero p{max-width:600px;margin:auto;color:var(--muted);font-size:1rem;line-height:1.75}.quick-info{display:flex;gap:9px;justify-content:center;flex-wrap:wrap;margin-top:20px}.quick-info span{padding:7px 11px;border:1px solid #302443;background:#151020;border-radius:99px;color:#cfc3e1;font-size:.8rem}
.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.card{min-width:0;background:linear-gradient(145deg,#191326,#100d19);border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:0 15px 40px #0004;transition:transform .2s,border-color .2s}.card:hover{transform:translateY(-5px);border-color:#8055c9}.preview{height:230px;padding:16px;overflow:hidden}.browser{height:100%;position:relative;overflow:hidden;border-radius:10px}.mock-content{height:100%;display:grid;grid-template-columns:1.15fr .7fr;align-items:center;gap:10px;padding:20px}.mock-tag{font-size:7px;font-weight:850;letter-spacing:1.5px;margin-bottom:9px;opacity:.8}.mock-name{font-size:clamp(17px,2vw,25px);line-height:1.02;font-weight:850;letter-spacing:-.7px;margin-bottom:8px}.mock-sub{font-size:8px;line-height:1.6;opacity:.8;max-width:170px}.mock-lines{display:flex;gap:4px;margin-top:12px}.mock-lines i{height:7px;width:25px;border-radius:99px;display:block}.mock-button{display:inline-block;margin-top:12px;padding:6px 9px;border-radius:5px;font-size:7px;font-weight:850}.mock-photo{width:min(100%,88px);aspect-ratio:4/5;display:flex;align-items:center;justify-content:center;margin:auto;font-size:34px}.mock-section{display:flex;gap:4px;margin-top:12px}.mock-section i{height:23px;flex:1;display:block;border-radius:4px}
.simple-preview{background:#f0eaff}.simple-preview .browser{background:#fff;border:1px solid #ded3f5;border-radius:3px}.simple-preview .mock-content{color:#292039}.simple-preview .mock-name{font-family:Georgia,serif;font-weight:500;font-size:27px}.simple-preview .mock-photo{background:#e4d7fb;color:#7752bd;border-radius:50% 50% 4px 4px}.simple-preview .mock-lines i,.simple-preview .mock-section i{background:#e9e1f5}.simple-preview .mock-button{background:#7654d6;color:#fff}.simple-preview .mock-tag{color:#7654d6}
.modern-preview{background:linear-gradient(135deg,#07151d,#102d37)}.modern-preview .browser{background:#09121b;border:1px solid #2dd4bf;border-radius:5px}.modern-preview .mock-content{color:#f0fdfa}.modern-preview .mock-name{font-family:ui-monospace,monospace;text-transform:uppercase;font-size:21px}.modern-preview .mock-photo{background:linear-gradient(145deg,#234052,#0f766e);color:#99f6e4;border:1px solid #2dd4bf;border-radius:13px;aspect-ratio:1}.modern-preview .mock-lines i,.modern-preview .mock-section i{background:#19343c;border-radius:2px}.modern-preview .mock-button{background:#2dd4bf;color:#062a2a;border-radius:3px}.modern-preview .mock-tag{color:#5eead4}
.creative-preview{background:radial-gradient(circle at 0 100%,#55216c,transparent 45%),radial-gradient(circle at 100% 0,#0e6672,transparent 45%),#111027}.creative-preview .browser{background:#111027;border:1px solid #7961cf;border-radius:17px;transform:rotate(-1deg);box-shadow:0 0 0 4px #7961cf22}.creative-preview .mock-content{color:#f7edff}.creative-preview .mock-name{background:linear-gradient(90deg,#f5edff,#a5f3fc,#f0abfc);background-clip:text;-webkit-background-clip:text;color:transparent;font-size:25px}.creative-preview .mock-photo{background:linear-gradient(145deg,#23616c,#5540a2 55%,#793b68);color:#ffe4f4;border-radius:26px 26px 7px 26px;transform:rotate(5deg);border:1px solid #8a6ce4}.creative-preview .mock-lines i{background:linear-gradient(90deg,#7654e8,#168ba0);border-radius:4px}.creative-preview .mock-section i{background:#302b50;border-radius:8px 2px}.creative-preview .mock-button{background:linear-gradient(100deg,#7654e8,#168ba0);color:#fff;border-radius:7px 2px}
.card-body{padding:20px}.heading{display:flex;align-items:center;justify-content:space-between;gap:8px}.card h2{font-size:1.15rem;margin:0;letter-spacing:-.3px}.tag{padding:5px 8px;border-radius:99px;background:#2c2040;color:#d8b4fe;font-size:.66rem;font-weight:850;white-space:nowrap}.card p{color:var(--muted);font-size:.88rem;line-height:1.65;margin:10px 0 18px;min-height:70px}.bottom{display:flex;align-items:center;justify-content:space-between;gap:10px}.swatches{display:flex}.swatches i{width:16px;height:16px;border-radius:50%;border:2px solid #171020;margin-left:-3px}.choose{display:inline-flex;align-items:center;gap:8px;padding:10px 12px;border-radius:10px;background:#7c3aed;color:white;font-size:.8rem;font-weight:850;white-space:nowrap}.choose:hover{filter:brightness(1.12)}.modern-card .choose{background:#0f766e}.creative-card .choose{background:linear-gradient(100deg,#7545d8,#167f91)}.note{margin-top:24px;text-align:center;border:1px solid var(--line);border-radius:13px;padding:15px;color:var(--muted);background:#120e1c;font-size:.88rem}.note strong{color:#e0caff}footer{text-align:center;padding:22px;color:#8d83a6;border-top:1px solid #302443;font-size:.8rem}
@media(max-width:850px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.card p{min-height:0}}@media(max-width:580px){.navbar{height:64px;padding:0 16px}.wrap{padding:38px 0 48px}.grid{grid-template-columns:1fr}.preview{height:240px}.card-body{padding:18px}.hero h1{letter-spacing:-1px}.card p{min-height:0}}
</style>
</head>
<body>
<header class="navbar"><a class="brand" href="/?page=home">Creatique<span>.</span></a><a class="nav-link" href="/?page=create">← Back to editor</a></header>
<main class="wrap">
<section class="hero">
<span class="eyebrow">✦ PROFESSIONAL PORTFOLIO DESIGNS</span>
<h1>Choose a style that <span>feels like you.</span></h1>
<p>Three distinct designs to present your profile, skills, projects, and experience with confidence.</p>
<div class="quick-info"><span>✓ 3 unique templates</span><span>▣ Responsive design</span><span>✦ Easy to customize</span></div>
</section>
<section class="grid" aria-label="Portfolio templates">
<article class="card simple-card">
<div class="preview simple-preview"><div class="browser"><div class="mock-content"><div><div class="mock-tag">HELLO, I'M</div><div class="mock-name">Your Name.</div><div class="mock-sub">A clear introduction, thoughtful work, and a clean personal profile.</div><div class="mock-lines"><i></i><i></i><i></i></div><span class="mock-button">VIEW MY WORK ↗</span></div><div><div class="mock-photo">✿</div><div class="mock-section"><i></i><i></i><i></i></div></div></div></div></div>
<div class="card-body"><div class="heading"><h2>Simple</h2><span class="tag">CLEAN & CLASSIC</span></div><p>A timeless, easy-to-read layout with soft purple accents and a focus on your information.</p><div class="bottom"><div class="swatches"><i style="background:#7654d6"></i><i style="background:#e4d7fb"></i><i style="background:#fff"></i></div><a class="choose" href="/?page=create&amp;template=simple">Use this style <span>→</span></a></div></div>
</article>
<article class="card modern-card">
<div class="preview modern-preview"><div class="browser"><div class="mock-content"><div><div class="mock-tag">AVAILABLE FOR PROJECTS</div><div class="mock-name">Build.<br>Ship.<br>Deliver.</div><div class="mock-sub">A bold, structured profile with crisp contrast and technical details.</div><div class="mock-lines"><i></i><i></i><i></i></div><span class="mock-button">EXPLORE PROJECTS ↗</span></div><div><div class="mock-photo">⌘</div><div class="mock-section"><i></i><i></i><i></i></div></div></div></div></div>
<div class="card-body"><div class="heading"><h2>Modern</h2><span class="tag" style="background:#14363b;color:#99f6e4">BOLD & POLISHED</span></div><p>A confident, contemporary style with deep navy surfaces, teal highlights, and a professional feel.</p><div class="bottom"><div class="swatches"><i style="background:#09121b"></i><i style="background:#2dd4bf"></i><i style="background:#234052"></i></div><a class="choose" href="/?page=create&amp;template=modern">Use this style <span>→</span></a></div></div>
</article>
<article class="card creative-card">
<div class="preview creative-preview"><div class="browser"><div class="mock-content"><div><div class="mock-tag">STUDIO WORK, CLEARLY PRESENTED</div><div class="mock-name">Create with<br>intention.</div><div class="mock-sub">A lively blend of violet, aqua, and gradient accents for expressive work.</div><div class="mock-lines"><i></i><i></i><i></i></div><span class="mock-button">SEE WHAT I CREATE ↗</span></div><div><div class="mock-photo">♡</div><div class="mock-section"><i></i><i></i><i></i></div></div></div></div></div>
<div class="card-body"><div class="heading"><h2>Creative</h2><span class="tag" style="background:#203044;color:#a5f3fc">COLORFUL & UNIQUE</span></div><p>An expressive, art-directed design with gradient details and an asymmetric layout to help your work stand out.</p><div class="bottom"><div class="swatches"><i style="background:#7654e8"></i><i style="background:#168ba0"></i><i style="background:#f0abfc"></i></div><a class="choose" href="/?page=create&amp;template=creative">Use this style <span>→</span></a></div></div>
</article>
</section>
<div class="note">💡 <strong>Not sure which to choose?</strong> Start with Simple. You can return and try another style anytime.</div>
</main>
<footer>© {{ date('Y') }} Creatique · A sharper presentation for your best work.</footer>
</body>
</html>
